name: Test

on:
  workflow_run:
      workflows: ['Train']
      types: [completed]
      branches:  [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      run: docker login -u vichu49x2 -p dckr_pat_bW_ru8VNuSfuYPeiHuxZyO5Mabs
    - name: Get the Docker image step 1
      run: image tag test:v1 vichu49x2/test:v1
    - name: Get the Docker image step 1
      run: docker pull vichu49x2/test:v1  
    - name: Test model
      run: |
        OUTPUT=$(python test.py)
        echo "Score:"
        echo "$OUTPUT"
        if [[ `echo "$OUTPUT 0.35" | awk '{print ($1 < $2)}'` == 1 ]]; then echo "Insufficient Accuracy" && exit 1; fi
    
