name: Train

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      run: docker login -u vichu49x2 -p dckr_pat_bW_ru8VNuSfuYPeiHuxZyO5Mabs
    - name: create image
      run: 
        docker build . -t test:v1
        docker image tag test:v1 vichu49x2/test:v1
        docker push vichu49x2/test:v1
      
